/** Pure helpers of the dsh runner: tool mapping, exit codes, the model/effort
 *  patch, the dumped selection, the version gate and failure messages. */
import { describe, expect, it } from 'vitest';
import {
  dshCanonicalTool,
  dshFailure,
  dshModelPatchYaml,
  dshShellExitCode,
  dshVersionSupported,
  parseDshLine,
  parseDumpedSelection,
} from '../../src/orgrt/dsh-runner-parse.js';
import { dshEffortFor } from '../../src/orgrt/dsh-runner-models.js';
import { dshArgs, dshPermissionMode } from '../../src/orgrt/dsh-runner-stream.js';

describe('dshCanonicalTool', () => {
  it('str_replace_editor maps per command', () => {
    expect(dshCanonicalTool('str_replace_editor', { command: 'view', path: '/a' })).toEqual({
      kind: 'read',
      input: { file_path: '/a' },
    });
    expect(dshCanonicalTool('str_replace_editor', { command: 'create', path: '/a', file_text: 'x' })).toEqual({
      kind: 'write',
      input: { file_path: '/a', content: 'x' },
    });
    expect(
      dshCanonicalTool('str_replace_editor', { command: 'str_replace', path: '/a', old_str: 'o', new_str: null }),
    ).toEqual({ kind: 'edit', input: { file_path: '/a', old_string: 'o', new_string: '' } });
    expect(dshCanonicalTool('str_replace_editor', { command: 'insert', path: '/a', insert_line: 2, new_str: 'n' })).toEqual({
      kind: 'patch',
      input: { files: [{ file_path: '/a', action: 'update' }] },
    });
  });

  it('shell, web, task, mcp and unknown tools', () => {
    expect(dshCanonicalTool('pwsh', { command: 'dir', description: 'd', workdir: 'C:\\x' })).toEqual({
      kind: 'shell',
      input: { command: 'dir', description: 'd', cwd: 'C:\\x' },
    });
    expect(dshCanonicalTool('web_search', { queries: ['a', 'b'] })).toEqual({ kind: 'web', input: { query: 'a\nb' } });
    expect(dshCanonicalTool('web_fetch', { url: 'https://x' })).toEqual({ kind: 'web', input: { url: 'https://x' } });
    expect(dshCanonicalTool('subagent', { task: 't' }).kind).toBe('task');
    expect(dshCanonicalTool('glob', { pattern: '*.ts' })).toEqual({ kind: 'search', input: { pattern: '*.ts' } });
    expect(dshCanonicalTool('mcp__mem__store', { k: 1 })).toEqual({
      kind: 'mcp',
      input: { server: 'mem', tool: 'store', arguments: { k: 1 } },
    });
    expect(dshCanonicalTool('job_output', { jobId: 'j' })).toEqual({ kind: 'other', input: { jobId: 'j' } });
  });
});

describe('dshShellExitCode', () => {
  const r = (result: string, extra = {}) => ({ type: 'tool_result' as const, status: 'completed' as const, result, ...extra });
  it('reads the marker, defaults to 0, and stays unknown when the command did not exit', () => {
    expect(dshShellExitCode(r('(no output)\n[exit code: 3]'))).toBe(3);
    expect(dshShellExitCode(r('hi\n'))).toBe(0);
    expect(dshShellExitCode(r('x\n[killed by signal: SIGTERM]'))).toBeUndefined();
    expect(dshShellExitCode(r('x\n[still running after 60000ms; moved to background job j1]\nThe command…'))).toBeUndefined();
    expect(dshShellExitCode(r('started background job j2'))).toBeUndefined();
    expect(dshShellExitCode(r('hi', { truncated: true }))).toBeUndefined();
    expect(dshShellExitCode({ type: 'tool_result', status: 'error', result: 'Error: x' })).toBeUndefined();
  });
});

describe('model + effort patch', () => {
  it('writes the whole agent-default-model config', () => {
    expect(dshModelPatchYaml({ provider: 'deepseek-official', model: 'deepseek-flash', reasoningEffort: 'low' })).toBe(
      [
        '# generated by monomind agent exec (dsh runner): model + effort for this run',
        '- id: agent-default-model',
        '  config:',
        '    provider: "deepseek-official"',
        '    model: "deepseek-flash"',
        '    reasoningEffort: "low"',
        '',
      ].join('\n'),
    );
    expect(dshModelPatchYaml({ provider: 'p', model: 'a: "b"' })).toContain('model: "a: \\"b\\""');
    expect(dshModelPatchYaml({ provider: 'p', model: 'm' })).not.toContain('reasoningEffort');
  });

  it('maps effort onto DeepSeek levels, verbatim elsewhere', () => {
    expect(['off', 'low', 'medium', 'high', 'xhigh', 'max'].map((e) => dshEffortFor('deepseek-official', 'deepseek-flash', e as any))).toEqual([
      'off',
      'low',
      'high',
      'high',
      'max',
      'max',
    ]);
    expect(dshEffortFor('deepseek-account', 'deepseek-flash', 'medium')).toBe('high');
    expect(dshEffortFor('openrouter', 'qwen/qwen3', 'medium')).toBe('medium');
  });

  it('reads the dumped selection, skipping !!js values', () => {
    const dump = [
      '- id: jobs',
      '- id: agent-default-model',
      "  name: '@deepseek-ai/dsh-agent-default-model'",
      '  config:',
      "    provider: 'deepseek-official'",
      '    model: !!js process.env.M',
      '    reasoningEffort: max',
      '- id: other',
      '  config:',
      '    model: nope',
    ].join('\n');
    expect(parseDumpedSelection(dump)).toEqual({ provider: 'deepseek-official', reasoningEffort: 'max' });
    expect(parseDumpedSelection('- id: x')).toEqual({});
  });
});

describe('invocation', () => {
  it('launcher flags precede --json', () => {
    expect(dshArgs('s1', '/t/p.yml')).toEqual(['--profile', 'headless', '--patch', '/t/p.yml', '--json', '--session-id', 's1', '-']);
    expect(dshArgs(undefined, undefined)).toEqual(['--profile', 'headless', '--json', '-']);
  });

  it('permission mode: full → danger-full-access, never inherited in scoped', () => {
    expect(dshPermissionMode({ access: 'full', env: {} })).toBe('danger-full-access');
    expect(dshPermissionMode({ access: 'scoped', env: { DSH_PERMISSION_MODE: 'danger-full-access' } })).toBe('workspace-write');
    expect(dshPermissionMode({ env: { DSH_PERMISSION_MODE: 'read-only' } })).toBe('read-only');
  });
});

describe('version gate', () => {
  it('accepts 0.1.7 (incl. rc) through 0.2.x', () => {
    expect(dshVersionSupported('0.1.7-rc.2\n')).toEqual({ ok: true, version: '0.1.7-rc.2' });
    expect(dshVersionSupported('0.2.0-rc.1').ok).toBe(true);
    expect(dshVersionSupported('0.1.6').ok).toBe(false);
    expect(dshVersionSupported('0.3.0').ok).toBe(false);
    expect(dshVersionSupported('garbage')).toEqual({ ok: false });
  });
});

describe('dshFailure / parseDshLine', () => {
  it('names subagent/fork refusals and passes other errors through', () => {
    const fork = dshFailure('session "s" is a subagent or forked session and cannot be driven directly', undefined, 's');
    expect(fork).toMatchObject({ fatal: true });
    expect(fork?.message).toMatch(/subagent or forked session.*Resume the parent/);
    expect(dshFailure("unknown option '--bogus'", undefined, undefined)).toEqual({
      fatal: false,
      message: "dsh: unknown option '--bogus'",
    });
    expect(dshFailure(undefined, { kind: 'aborted' }, undefined)).toEqual({
      fatal: false,
      message: 'dsh: turn aborted: aborted',
    });
    expect(dshFailure(undefined, { kind: 'completed' }, undefined)).toBeNull();
  });

  it('parses only event lines', () => {
    expect(parseDshLine('dsh: reasoning:')).toBeNull();
    expect(parseDshLine('{"type":"final","text":"x"}')).toEqual({ type: 'final', text: 'x' });
    expect(parseDshLine('{not json')).toBeNull();
  });
});
