/**
 * Helper script generator: hook-handler.cjs fallback content.
 */

/**
 * Generate hook-handler.cjs (cross-platform hook dispatcher)
 * This is the inline fallback when file copy from the package fails.
 * Uses string concatenation instead of template literals to avoid escaping issues.
 */
export function generateHookHandler(): string {
  // Build as array of lines to avoid template-in-template escaping nightmares
  const lines = [
    '#!/usr/bin/env node',
    '/**',
    ' * Monomind Hook Handler (Cross-Platform)',
    ' * Dispatches hook events to the appropriate helper modules.',
    ' */',
    '',
    "const path = require('path');",
    "const fs = require('fs');",
    '',
    'const helpersDir = __dirname;',
    '',
    '// PreToolUse context reaches the model only as JSON additionalContext (#409).',
    'function emitPreToolUseContext(lines) {',
    '  if (!lines.length || process.exitCode === 2) return;',
    '  process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", additionalContext: lines.join("\\n") } }) + "\\n");',
    '}',
    '',
    '// Graph gate (#413): a one-time nudge toward monograph, never a block. Only',
    '// source searches count: not piped greps, not dependency/build/log/doc paths.',
    'function isNonSourcePath(p) {',
    '  p = String(p || "").replace(/^[\'"]+|[\'"]+$/g, "");',
    '  if (!p) return false;',
    '  if (p[0] === "~" || p.indexOf("$HOME") === 0) return true;',
    '  if (p[0] === "/" && p.indexOf(process.cwd() + "/") !== 0) return true;',
    '  return /(?:^|\\/)(?:node_modules|dist|build|coverage|\\.git|\\.monomind)(?:\\/|$)|\\.(?:log|txt|md|json|jsonl|lock|csv|ya?ml|env|out|xml|html?)$/i.test(p);',
    '}',
    'function isSourceSearchCommand(cmd) {',
    '  if (/(?:^|[^|])\\|\\s*(?:grep|rg|ag)\\b/.test(cmd)) return false;',
    '  var tokens = cmd.replace(/\\d*[<>]+&?\\s*\\S+/g, " ").split(/\\s+/);',
    '  for (var i = 0; i < tokens.length; i++) {',
    '    var t = tokens[i];',
    '    if (t[0] === "-") { var eq = t.indexOf("="); if (eq < 0) continue; t = t.slice(eq + 1); }',
    '    if (isNonSourcePath(t)) return false;',
    '  }',
    '  return true;',
    '}',
    'function graphNudgeOnce(sessId, isSourceSearch) {',
    '  if (!sessId || !isSourceSearch) return null;',
    '  try { if (!fs.statSync(path.join(process.cwd(), ".monomind", "monograph.db")).size) return null; } catch (e) { return null; }',
    '  var stateFile = path.join(process.cwd(), ".monomind", "graph-gate-state.json");',
    '  var gateState = {};',
    '  try { gateState = JSON.parse(fs.readFileSync(stateFile, "utf-8")); } catch (e) {}',
    '  var sessions = (gateState && typeof gateState.sessions === "object") ? gateState.sessions : {};',
    '  var s = sessions[sessId] || { queried: false, nudged: false };',
    '  if (s.queried || s.nudged) return null;',
    '  s.nudged = true; s.ts = Date.now(); sessions[sessId] = s;',
    '  try { fs.mkdirSync(path.dirname(stateFile), { recursive: true }); fs.writeFileSync(stateFile, JSON.stringify({ sessions: sessions })); } catch (e) {}',
    '  return "[MONOGRAPH_REMINDER] This project has a code graph. For symbol and file lookups, mcp__monomind__monograph_query / monograph_suggest return file:line directly. Shown once per session.";',
    '}',
    '',
    'function safeRequire(modulePath) {',
    '  try {',
    '    if (fs.existsSync(modulePath)) {',
    '      const origLog = console.log;',
    '      const origError = console.error;',
    '      console.log = () => {};',
    '      console.error = () => {};',
    '      try {',
    '        const mod = require(modulePath);',
    '        return mod;',
    '      } finally {',
    '        console.log = origLog;',
    '        console.error = origError;',
    '      }',
    '    }',
    '  } catch (e) {',
    '    // silently fail',
    '  }',
    '  return null;',
    '}',
    '',
    "const router = safeRequire(path.join(helpersDir, 'router.cjs'));",
    "const session = safeRequire(path.join(helpersDir, 'session.cjs'));",
    "const memory = safeRequire(path.join(helpersDir, 'memory.cjs'));",
    "const intelligence = safeRequire(path.join(helpersDir, 'intelligence.cjs'));",
    '',
    'const [,, command, ...args] = process.argv;',
    '',
    '// Read stdin with timeout — Claude Code sends hook data as JSON via stdin.',
    '// Timeout prevents hanging when stdin is in an ambiguous state (not TTY, not pipe).',
    'async function readStdin() {',
    '  if (process.stdin.isTTY) return "";',
    '  return new Promise((resolve) => {',
    '    let data = "";',
    '    const timer = setTimeout(() => {',
    '      process.stdin.removeAllListeners();',
    '      process.stdin.pause();',
    '      resolve(data);',
    '    }, 500);',
    '    process.stdin.setEncoding("utf8");',
    '    process.stdin.on("data", (chunk) => { data += chunk; });',
    '    process.stdin.on("end", () => { clearTimeout(timer); resolve(data); });',
    '    process.stdin.on("error", () => { clearTimeout(timer); resolve(data); });',
    '    process.stdin.resume();',
    '  });',
    '}',
    '',
    'async function main() {',
    '  let stdinData = "";',
    '  try { stdinData = await readStdin(); } catch (e) { /* ignore */ }',
    '  let hookInput = {};',
    '  if (stdinData.trim()) {',
    '    try { hookInput = JSON.parse(stdinData); } catch (e) { /* ignore */ }',
    '  }',
    '  // Prefer stdin fields, then env, then argv',
    "  var prompt = hookInput.prompt || hookInput.command || hookInput.toolInput || process.env.PROMPT || process.env.TOOL_INPUT_command || args.join(' ') || '';",
    '',
    'const handlers = {',
    "  'route': () => {",
    '    if (intelligence && intelligence.getContext) {',
    '      try {',
    '        const ctx = intelligence.getContext(prompt);',
    '        if (ctx) console.log(ctx);',
    '      } catch (e) { /* non-fatal */ }',
    '    }',
    '    if (router && router.routeTask) {',
    '      const result = router.routeTask(prompt);',
    '      var output = [];',
    "      output.push('[INFO] Routing task: ' + (prompt.substring(0, 80) || '(no prompt)'));",
    "      output.push('');",
    "      output.push('+------------ monomind | Primary Recommendation -------------+');",
    "      output.push('| Agent: ' + result.agent.padEnd(53) + '|');",
    "      output.push('| Confidence: ' + (result.confidence * 100).toFixed(1) + '%' + ' '.repeat(44) + '|');",
    "      output.push('| Reason: ' + result.reason.substring(0, 53).padEnd(53) + '|');",
    "      output.push('+--------------------------------------------------------------+');",
    "      console.log(output.join('\\n'));",
    '      // Monograph knowledge graph suggestion for architecture/understanding tasks',
    '      try {',
    "        var archKeywords = ['understand', 'architecture', 'how does', 'what calls', 'dependency', 'depends on', 'flow', 'how is', 'explain codebase', 'project structure', 'what is the relationship', 'graph', 'knowledge'];",
    '        var promptLower = prompt.toLowerCase();',
    '        var isArchQuery = archKeywords.some(function(k) { return promptLower.includes(k); });',
    "        var graphJson = require('path').join(process.cwd(), '.monomind', 'monograph.db');",
    "        var hasGraph = require('fs').existsSync(graphJson);",
    '        if (isArchQuery) {',
    '          var gfOutput = [];',
    "          gfOutput.push('');",
    "          gfOutput.push('+------- monograph | Knowledge Graph Available ---------------+');",
    '          if (hasGraph) {',
    "            gfOutput.push('| Graph: .monomind/monograph.db                               |');",
    "            gfOutput.push('| Use: mcp__monomind__monograph_god_nodes                    |');",
    "            gfOutput.push('|      mcp__monomind__monograph_query                        |');",
    "            gfOutput.push('|      mcp__monomind__monograph_shortest_path                |');",
    "            gfOutput.push('| Tip: Call monograph_god_nodes first for architecture overview|');",
    '          } else {',
    "            gfOutput.push('| No graph found. Build with:                                 |');",
    "            gfOutput.push('|   mcp__monomind__monograph_build                            |');",
    '          }',
    "          gfOutput.push('+--------------------------------------------------------------+');",
    "          console.log(gfOutput.join('\\n'));",
    '        }',
    '      } catch (e) { /* non-fatal */ }',
    '    } else {',
    "      console.log('[INFO] Router not available, using default routing');",
    '    }',
    '  },',
    '',
    "  'pre-bash': () => {",
    '    var cmd = (hookInput.toolInput || hookInput.tool_input || {}).command || hookInput.command || "";',
    '    if (typeof cmd !== "string") cmd = "";',
    '    var isGrep = /\\b(?:grep|rg|ag|find|fd)\\b/.test(cmd);',
    '    if (!isGrep) return;',
    '    var hintLines = [];',
    '    // Graph gate (#413): one-time nudge, never a block',
    '    var dbPath = path.join(process.cwd(), ".monomind", "monograph.db");',
    '    var nudge = graphNudgeOnce(hookInput.sessionId || hookInput.session_id, isSourceSearchCommand(cmd));',
    '    if (nudge) hintLines.push(nudge);',
    '    // Graph-assisted grep: resolve patterns via monograph DB',
    '    try {',
    '      if (!fs.existsSync(dbPath)) return;',
    '      var Database;',
    '      try { Database = require("better-sqlite3"); } catch(e) {',
    '        try { Database = require(path.join(process.cwd(), "node_modules/.pnpm/node_modules/better-sqlite3")); } catch(e2) {',
    '          try { Database = require(path.join(process.cwd(), "node_modules/better-sqlite3")); } catch(e3) { return; }',
    '        }',
    '      }',
    '      var db = new Database(dbPath, { readonly: true });',
    '      try {',
    '        // Extract bare words (identifiers or filenames) from the command',
    '        var words = cmd.match(/[a-zA-Z_$][a-zA-Z0-9_$]{3,}/g) || [];',
    '        var stop = {import:1,export:1,from:1,require:1,return:1,function:1,const:1,let:1,var:1,class:1,type:1,error:1,string:1,number:1,object:1,boolean:1,value:1,result:1,data:1,name:1,path:1,file:1,node:1,config:1,index:1,module:1,handler:1,default:1,grep:1,include:1,exclude:1};',
    '        for (var wi = 0; wi < words.length; wi++) {',
    '          var w = words[wi];',
    '          if (stop[w.toLowerCase()]) continue;',
    "          var row = db.prepare(\"SELECT name, file_path, start_line FROM nodes WHERE name = ? COLLATE NOCASE AND label NOT IN ('Concept','Community','Folder','Variable') AND file_path IS NOT NULL AND file_path NOT LIKE '%.md' LIMIT 1\").get(w);",
    '          if (row) {',
    '            hintLines.push("[MONOGRAPH_HINT] " + row.name + " found at " + row.file_path + (row.start_line != null ? ":" + row.start_line : ""));',
    '            break;',
    '          }',
    '        }',
    '      } finally { try { db.close(); } catch(e) {} }',
    '    } catch (e) { /* non-fatal */ } finally { emitPreToolUseContext(hintLines); }',
    '  },',
    '',
    "  'pre-search': () => {",
    '    // Graph gate for Grep/Glob tools (same one-time nudge as pre-bash)',
    '    var ti = hookInput.toolInput || hookInput.tool_input || {};',
    '    var tool = hookInput.toolName || hookInput.tool_name || "";',
    '    var paths = [ti.path, ti.glob, tool === "Glob" ? ti.pattern : ""];',
    '    var nudge = graphNudgeOnce(hookInput.sessionId || hookInput.session_id, !paths.some(isNonSourcePath));',
    '    if (nudge) emitPreToolUseContext([nudge]);',
    '  },',
    '',
    "  'pre-write': () => {",
    '    // Stub — real implementation in the full hook-handler.cjs',
    '  },',
    '',
    "  'post-edit': () => {",
    '    if (session && session.metric) {',
    "      try { session.metric('edits'); } catch (e) { /* no active session */ }",
    '    }',
    '    if (intelligence && intelligence.recordEdit) {',
    '      try {',
    "        var file = process.env.TOOL_INPUT_file_path || args[0] || '';",
    '        intelligence.recordEdit(file);',
    '      } catch (e) { /* non-fatal */ }',
    '    }',
    '    // Auto-rebuild monograph knowledge graph for code file changes',
    '    try {',
    "      var editedFile = process.env.TOOL_INPUT_file_path || args[0] || '';",
    '      var isCode = /\\.(ts|js|tsx|jsx|py|go|rs|java|c|cpp|h|cs|rb|php|swift|kt|scala)$/.test(editedFile);',
    "      var dbFile = require('path').join(process.cwd(), '.monomind', 'monograph.db');",
    "      if (isCode && require('fs').existsSync(dbFile)) {",
    "        var s = `import { buildAsync } from '@monoes/monograph'; buildAsync(${JSON.stringify(process.cwd())}).catch(()=>{});`;",
    "        require('child_process').spawn(process.execPath, ['--input-type=module', '--eval', s], {",
    "          detached: true, stdio: 'ignore'",
    '        }).unref();',
    "        console.log('[MONOGRAPH] Queued graph rebuild for: ' + require('path').basename(editedFile));",
    '      }',
    '    } catch (e) { /* non-fatal — monograph may not be installed */ }',
    "    console.log('[OK] Edit recorded');",
    '  },',
    '',
    "  'session-restore': () => {",
    '    if (session) {',
    '      var existing = session.restore && session.restore();',
    '      if (!existing) {',
    '        session.start && session.start();',
    '      }',
    '    } else {',
    "      console.log('[OK] Session restored: session-' + Date.now());",
    '    }',
    '    if (intelligence && intelligence.init) {',
    '      try {',
    '        var result = intelligence.init();',
    '        if (result && result.nodes > 0) {',
    "          console.log('[INTELLIGENCE] Loaded ' + result.nodes + ' patterns, ' + result.edges + ' edges');",
    '        }',
    '      } catch (e) { /* non-fatal */ }',
    '    }',
    '  },',
    '',
    "  'post-graph-tool': () => {",
    '    // Clear the graph gate when a real monograph tool is called',
    '    var sessId = hookInput.sessionId || hookInput.session_id || "";',
    '    if (!sessId) return;',
    '    var stateFile = path.join(process.cwd(), ".monomind", "graph-gate-state.json");',
    '    try {',
    '      var gateState = {};',
    '      try { gateState = JSON.parse(fs.readFileSync(stateFile, "utf-8")); } catch(e) {}',
    '      var sessions = (gateState && typeof gateState.sessions === "object") ? gateState.sessions : {};',
    '      var s = sessions[sessId] || { nudged: false };',
    '      s.queried = true; s.ts = Date.now(); sessions[sessId] = s;',
    '      fs.writeFileSync(stateFile, JSON.stringify({ sessions: sessions }));',
    '    } catch(e) {}',
    '  },',
    '',
    "  'session-end': () => {",
    '    if (intelligence && intelligence.consolidate) {',
    '      try {',
    '        var result = intelligence.consolidate();',
    '        if (result && result.entries > 0) {',
    "          var msg = '[INTELLIGENCE] Consolidated: ' + result.entries + ' entries, ' + result.edges + ' edges';",
    "          if (result.newEntries > 0) msg += ', ' + result.newEntries + ' new';",
    "          msg += ', PageRank recomputed';",
    '          console.log(msg);',
    '        }',
    '      } catch (e) { /* non-fatal */ }',
    '    }',
    '    if (session && session.end) {',
    '      session.end();',
    '    } else {',
    "      console.log('[OK] Session ended');",
    '    }',
    '    // KG nudge: prompt agent to distill session knowledge before exiting',
    "    if (process.env.MONOMIND_KG_NUDGE !== 'false') {",
    "      console.log('[KG_NUDGE] Session ending — consider distilling key insights into the knowledge graph:');",
    "      console.log('[KG_NUDGE]   1. Identify 2-5 important entities (functions, patterns, decisions) from this session');",
    "      console.log('[KG_NUDGE]   2. Call memory_kg_ingest with nodes [{name, type, description}], edges [{source, target, relation}],');",
    "      console.log('[KG_NUDGE]      and any durable rules [{rule, context}] — use the session ID as originRef');",
    "      console.log('[KG_NUDGE]   3. Check existing entities first: memory_kg_stats with glossary:true');",
    "      console.log('[KG_NUDGE]   Skip for trivial sessions. Disable with MONOMIND_KG_NUDGE=false');",
    '    }',
    '  },',
    '',
    "  'pre-task': () => {",
    '    if (session && session.metric) {',
    "      try { session.metric('tasks'); } catch (e) { /* no active session */ }",
    '    }',
    '    if (router && router.routeTask && prompt) {',
    '      var result = router.routeTask(prompt);',
    "      console.log('[INFO] Task routed to: ' + result.agent + ' (confidence: ' + result.confidence + ')');",
    '    } else {',
    "      console.log('[OK] Task started');",
    '    }',
    '  },',
    '',
    "  'post-task': () => {",
    '    if (intelligence && intelligence.feedback) {',
    '      try {',
    '        intelligence.feedback(true);',
    '      } catch (e) { /* non-fatal */ }',
    '    }',
    "    console.log('[OK] Task completed');",
    '  },',
    '',
    "  'compact-manual': () => {",
    "    console.log('PreCompact Guidance:');",
    "    console.log('IMPORTANT: Review CLAUDE.md in project root for:');",
    "    console.log('   - Available agents and concurrent usage patterns');",
    "    console.log('   - Swarm coordination strategies (hierarchical, mesh, adaptive)');",
    "    console.log('   - Critical concurrent execution rules (1 MESSAGE = ALL OPERATIONS)');",
    "    console.log('Ready for compact operation');",
    '  },',
    '',
    "  'compact-auto': () => {",
    "    console.log('Auto-Compact Guidance (Context Window Full):');",
    "    console.log('CRITICAL: Before compacting, ensure you understand:');",
    "    console.log('   - All agents available in .claude/agents/ directory');",
    "    console.log('   - Concurrent execution patterns from CLAUDE.md');",
    "    console.log('   - Swarm coordination strategies for complex tasks');",
    "    console.log('Apply GOLDEN RULE: Always batch operations in single messages');",
    "    console.log('Auto-compact proceeding with full agent context');",
    '  },',
    '',
    "  'status': () => {",
    "    console.log('[OK] Status check');",
    '  },',
    '',
    "  'stats': () => {",
    '    if (intelligence && intelligence.stats) {',
    "      intelligence.stats(args.includes('--json'));",
    '    } else {',
    "      console.log('[WARN] Intelligence module not available. Run session-restore first.');",
    '    }',
    '  },',
    '};',
    '',
    'if (command && handlers[command]) {',
    '  try {',
    '    handlers[command]();',
    '  } catch (e) {',
    "    console.log('[WARN] Hook ' + command + ' encountered an error: ' + e.message);",
    '  }',
    '} else if (command) {',
    "  console.log('[OK] Hook: ' + command);",
    '} else {',
    "  console.log('Usage: hook-handler.cjs <route|pre-bash|post-edit|session-restore|session-end|pre-task|post-task|compact-manual|compact-auto|status|stats>');",
    '}',
    '} // end main',
    '',
    'process.exitCode = 0;',
    "// Keep a gate's exit 2 (block) — an unconditional exit(0) would swallow it (#446).",
    'main().catch(() => {}).finally(() => { process.exit(process.exitCode ?? 0); });',
  ];
  return `${lines.join('\n')}\n`;
}
