/**
 * kimi-code statusline (footer under the chatbox).
 * File-size sweep: split out of kimi-generator.ts.
 *
 * Kimi supports a custom status line: [status_line].command in
 * ~/.kimi-code/tui.toml. Kimi runs the command with a JSON snapshot on stdin
 * (model, cwd, git branch, permission mode, plan mode, context usage,
 * session id, version) and renders the FIRST stdout line as the footer.
 * Runs are capped at 300ms and throttled to once per second; a failure (or
 * no output) falls back to the built-in layout, so this script exits quietly
 * whenever the project has no monomind statusline.
 */

/**
 * Generate ~/.kimi-code/statusline.sh — reads the cwd out of kimi's stdin
 * JSON snapshot and delegates to that project's monomind statusline helper,
 * joining its multi-line output into the single footer line kimi renders.
 * Exits 0 with no output when there's nothing to show (kimi then keeps its
 * built-in layout).
 *
 * The script must be free of backticks and ${...} outside its own template
 * usage — it is embedded into a TypeScript template literal by the caller.
 */
export function generateKimiStatuslineSh(): string {
  // NOTE for editors: this is a TS template literal — every \${...} below is
  // an escaped shell expansion, not a JS interpolation. $(...) is safe.
  return `#!/usr/bin/env bash
# monomind statusline for Kimi Code (generated by monomind init --kimicode).
#
# Kimi caps status_line commands at 300ms and throttles them to 1/sec, but the
# full node renderer needs ~500ms. A synchronous render is therefore ALWAYS
# killed and kimi permanently falls back to its built-in layout. So this
# wrapper never renders inline: it prints the last cached line instantly and
# refreshes the cache in a detached background job every few seconds.
#
# Kimi renders ONLY the first stdout line as the footer, but the monomind
# renderer outputs 4+ lines. So the background refresh joins all content
# lines (skipping the ─── separator lines) into a single line for the cache.
INPUT=$(cat)

# Cheap cwd extraction (no node startup — that alone costs ~50ms of the cap).
PROJECT_DIR=$(printf '%s' "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -1)
[ -z "$PROJECT_DIR" ] && PROJECT_DIR=$(printf '%s' "$INPUT" | sed -n 's/.*"\\(working_dir\\|project_dir\\)"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\2/p' | head -1)
[ -z "$PROJECT_DIR" ] && PROJECT_DIR="$(pwd)"

CACHE_DIR="\${TMPDIR:-/tmp}/monomind-kimi-statusline"
CACHE="$CACHE_DIR/$(printf '%s' "$PROJECT_DIR" | cksum | cut -d' ' -f1)"
TTL=3

now=$(date +%s)
mtime=0
if [ -f "$CACHE" ]; then
  mtime=$(stat -f %m "$CACHE" 2>/dev/null || stat -c %Y "$CACHE" 2>/dev/null || echo 0)
  cat "$CACHE"
fi

if [ $((now - mtime)) -ge $TTL ]; then
  mkdir -p "$CACHE_DIR" 2>/dev/null
  (
    LINE=""
    # Join all rendered lines into one (kimi reads only the first stdout
    # line); drop the pure ─── separator lines first.
    if [ -f "$PROJECT_DIR/.claude/helpers/statusline.cjs" ]; then
      LINE=$(CLAUDE_PROJECT_DIR="$PROJECT_DIR" node "$PROJECT_DIR/.claude/helpers/statusline.cjs" 2>/dev/null | grep -v '──' | paste -sd' ' -)
    elif [ -f "$PROJECT_DIR/.gemini/helpers/statusline.cjs" ]; then
      LINE=$(CLAUDE_PROJECT_DIR="$PROJECT_DIR" node "$PROJECT_DIR/.gemini/helpers/statusline.cjs" 2>/dev/null | grep -v '──' | paste -sd' ' -)
    fi
    [ -n "$LINE" ] && printf '%s\\n' "$LINE" > "$CACHE.tmp" && mv "$CACHE.tmp" "$CACHE"
  ) >/dev/null 2>&1 &
fi
# First run (cold cache) prints nothing — kimi falls back to its built-in
# layout for a second or two until the background refresh lands.
exit 0
`;
}

/**
 * Merge [status_line].command into a tui.toml file WITHOUT clobbering:
 * - existing [status_line] with a command → unchanged (user's choice wins)
 * - existing [status_line] without a command → command inserted into the section
 * - no [status_line] section → appended at the end
 * Anything else in the file is preserved byte-for-byte.
 */
export function mergeKimiTuiTomlStatusline(existing: string, command: string): string {
  const sectionRe = /^\s*\[status_line\]\s*$/m;
  const commandLine = `command = "${command}"`;

  if (sectionRe.test(existing)) {
    const sectionStart = existing.search(sectionRe);
    // Find the end of this section: next [section] header or EOF
    const rest = existing.slice(sectionStart);
    const nextSection = rest.slice(rest.indexOf('\n') + 1).search(/^\s*\[/m);
    const sectionEnd =
      nextSection === -1 ? existing.length : sectionStart + rest.indexOf('\n') + 1 + nextSection;
    const section = existing.slice(sectionStart, sectionEnd);
    if (/^\s*command\s*=/m.test(section)) return existing; // user already has one
    return (
      existing.slice(0, sectionEnd).replace(/\s*$/, '\n') +
      commandLine +
      '\n' +
      existing.slice(sectionEnd)
    );
  }

  const sep = existing.length && !existing.endsWith('\n') ? '\n' : '';
  return `${existing + sep + (existing.length ? '\n' : '')}[status_line]\n${commandLine}\n`;
}
